;ATLAS CPU-16 Microcode v1.0
;Hayden Buscher - 2022

;PC_ST, OP1_ST, OP2_ST, IR_ST, MDR_ST, MEM_ST, REG1_ST, REG2_ST, SP_ST, STAT_ST
;F_DOUT, PC_DOUT, SWP_DOUT, WRD_DOUT, MDR_DOUT, MEM_DOUT, VECT_DOUT, REG1_DOUT, REG2_DOUT, SP_DOUT
;PC_AOUT, MAR_AOUT
;COND_N, COND_Z, COND_V, COND_C
;ALU_ADD, ALU_ADC, ALU_SUB, ALU_SBB, ALU_AND, ALU_OR, ALU_XOR, ALU_NOT, ALU_LSH, ALU_RSH, ALU_INC, ALU_DEC, ALU_SEX
;PC_INC, COND_NEG
;F_ALUIN, F_ST
;MAR_ST, IRQ_EN
;MODE_RST, MODE_DMA, MODE_FLT, MODE_FETCH

$000
MODE_RST,F_ST,STAT_ST,@RST	;000 - RST

$78
PC_INC,@MOV_#m_REG

$408																				
.@FETCH
MODE_FETCH,IRQ_EN,PC_AOUT,MEM_DOUT,IR_ST

.@INC_PC_END
PC_INC,@FETCH

.@RST
MODE_RST,WRD_DOUT,MAR_ST,+1
MODE_RST,MAR_AOUT,MEM_DOUT,PC_ST,@FETCH

.@MOV_#m_REG
PC_AOUT,MEM_DOUT,REG2_ST,@INC_PC_END