;ATLAS CPU-16 Microcode v1.0
;Hayden Buscher - 2022

;PC_ST, OP1_ST, OP2_ST, IR_ST, MDR_ST, MEM_ST, REG1_ST, REG2_ST, SP_ST, STAT_ST
;F_DOUT, PC_DOUT, SWP_DOUT, WRD_DOUT, MDR_DOUT, MEM_DOUT, VECT_DOUT, REG1_DOUT, REG2_DOUT, SP_DOUT
;PC_AOUT, MAR_AOUT
;COND_N, COND_Z, COND_V, COND_C
;ALU_ADD, ALU_ADC, ALU_SUB, ALU_SBB, ALU_AND, ALU_OR, ALU_XOR, ALU_NOT, ALU_LSH, ALU_RSH, ALU_INC, ALU_DEC, ALU_SEX
;PC_INC, COND_POS
;F_ALUIN, F_ST
;MAR_ST, IRQ_EN
;MODE_RST, MODE_DMA, MODE_FLT, MODE_FETCH

;First half of mCode ROM
$0
MODE_RST,F_ST,STAT_ST,@RST	;0000 - RST
PC_INC,@HLT	;0001 - HLT

$2D
PC_INC,COND_Z,@JMP_#m_REL	;0055 - BNE $m(PC)

$40
REG1_DOUT,MDR_ST,PC_INC,@MOV_REG_REG	;0100 - MOV [reg],[reg]
REG1_DOUT,MDR_ST,PC_INC,@MOV_REG_DIR	;0101 - MOV [reg],$m

$69
PC_INC,REG1_DOUT,MAR_ST,OP1_ST,@MOV_PINC_DIR	;0151 - MOV (reg)+,$m

$78
PC_INC,@MOV_#m_REG	;0170 - MOV #m,[reg]

$27B
PC_INC,@CMP_#m_IREG	;1173 - CMP #m,(reg)

;Second half of mCode ROM
$403
.@INC_PC_END
PC_INC,@FETCH

$408																				
.@FETCH
MODE_FETCH,IRQ_EN,PC_AOUT,MEM_DOUT,IR_ST

.@RST
MODE_RST,WRD_DOUT,MAR_ST,+1
MODE_RST,MAR_AOUT,MEM_DOUT,PC_ST,@FETCH

.@HLT
IRQ_EN,@HLT

.@JMP_#m_REL
PC_DOUT,OP1_ST,+1
PC_AOUT,MEM_DOUT,OP2_ST,+1
ALU_ADD,PC_ST,@FETCH

.@MOV_REG_REG
MDR_DOUT,REG2_ST,@FETCH

.@MOV_REG_DIR
PC_AOUT,MDR_DOUT,MEM_ST,@INC_PC_END

.@MOV_PINC_DIR
MAR_AOUT,MEM_DOUT,MDR_ST,+1
PC_AOUT,MEM_DOUT,MAR_ST,+1
PC_INC,MDR_DOUT,MAR_AOUT,MEM_ST,+1
ALU_INC,REG1_ST,@FETCH

.@MOV_#m_REG
PC_AOUT,MEM_DOUT,REG2_ST,@INC_PC_END

.@CMP_#m_IREG
PC_AOUT,MEM_DOUT,OP1_ST,+1
PC_INC,REG2_DOUT,MAR_ST,+1
MAR_AOUT,MEM_DOUT,OP2_ST,+1
ALU_SUB,F_ST,@FETCH